/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardsIndexRouteImport } from './routes/boards.index'
import { Route as BoardsBoardIdRouteImport } from './routes/boards.$boardId'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as BoardsBoardIdIndexRouteImport } from './routes/boards.$boardId.index'
import { Route as BoardsBoardIdArchiveRouteImport } from './routes/boards.$boardId.archive'
import { Route as BoardsBoardIdSettingsRouteImport } from './routes/boards.$boardId.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsIndexRoute = BoardsIndexRouteImport.update({
  id: '/boards/',
  path: '/boards/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardIdRoute = BoardsBoardIdRouteImport.update({
  id: '/boards/$boardId',
  path: '/boards/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardIdIndexRoute = BoardsBoardIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardsBoardIdRoute,
} as any)
const BoardsBoardIdArchiveRoute = BoardsBoardIdArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => BoardsBoardIdRoute,
} as any)
const BoardsBoardIdSettingsRoute = BoardsBoardIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BoardsBoardIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boards/$boardId': typeof BoardsBoardIdRouteWithChildren
  '/share/$token': typeof ShareTokenRoute
  '/boards/': typeof BoardsIndexRoute
  '/boards/$boardId/archive': typeof BoardsBoardIdArchiveRoute
  '/boards/$boardId/settings': typeof BoardsBoardIdSettingsRoute
  '/boards/$boardId/': typeof BoardsBoardIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/share/$token': typeof ShareTokenRoute
  '/boards': typeof BoardsIndexRoute
  '/boards/$boardId/archive': typeof BoardsBoardIdArchiveRoute
  '/boards/$boardId/settings': typeof BoardsBoardIdSettingsRoute
  '/boards/$boardId': typeof BoardsBoardIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boards/$boardId': typeof BoardsBoardIdRouteWithChildren
  '/share/$token': typeof ShareTokenRoute
  '/boards/': typeof BoardsIndexRoute
  '/boards/$boardId/archive': typeof BoardsBoardIdArchiveRoute
  '/boards/$boardId/settings': typeof BoardsBoardIdSettingsRoute
  '/boards/$boardId/': typeof BoardsBoardIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boards/$boardId'
    | '/share/$token'
    | '/boards/'
    | '/boards/$boardId/archive'
    | '/boards/$boardId/settings'
    | '/boards/$boardId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/share/$token'
    | '/boards'
    | '/boards/$boardId/archive'
    | '/boards/$boardId/settings'
    | '/boards/$boardId'
  id:
    | '__root__'
    | '/'
    | '/boards/$boardId'
    | '/share/$token'
    | '/boards/'
    | '/boards/$boardId/archive'
    | '/boards/$boardId/settings'
    | '/boards/$boardId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardsBoardIdRoute: typeof BoardsBoardIdRouteWithChildren
  ShareTokenRoute: typeof ShareTokenRoute
  BoardsIndexRoute: typeof BoardsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/': {
      id: '/boards/'
      path: '/boards'
      fullPath: '/boards/'
      preLoaderRoute: typeof BoardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$boardId': {
      id: '/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof BoardsBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$boardId/': {
      id: '/boards/$boardId/'
      path: '/'
      fullPath: '/boards/$boardId/'
      preLoaderRoute: typeof BoardsBoardIdIndexRouteImport
      parentRoute: typeof BoardsBoardIdRoute
    }
    '/boards/$boardId/archive': {
      id: '/boards/$boardId/archive'
      path: '/archive'
      fullPath: '/boards/$boardId/archive'
      preLoaderRoute: typeof BoardsBoardIdArchiveRouteImport
      parentRoute: typeof BoardsBoardIdRoute
    }
    '/boards/$boardId/settings': {
      id: '/boards/$boardId/settings'
      path: '/settings'
      fullPath: '/boards/$boardId/settings'
      preLoaderRoute: typeof BoardsBoardIdSettingsRouteImport
      parentRoute: typeof BoardsBoardIdRoute
    }
  }
}

interface BoardsBoardIdRouteChildren {
  BoardsBoardIdArchiveRoute: typeof BoardsBoardIdArchiveRoute
  BoardsBoardIdSettingsRoute: typeof BoardsBoardIdSettingsRoute
  BoardsBoardIdIndexRoute: typeof BoardsBoardIdIndexRoute
}

const BoardsBoardIdRouteChildren: BoardsBoardIdRouteChildren = {
  BoardsBoardIdArchiveRoute: BoardsBoardIdArchiveRoute,
  BoardsBoardIdSettingsRoute: BoardsBoardIdSettingsRoute,
  BoardsBoardIdIndexRoute: BoardsBoardIdIndexRoute,
}

const BoardsBoardIdRouteWithChildren = BoardsBoardIdRoute._addFileChildren(
  BoardsBoardIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardsBoardIdRoute: BoardsBoardIdRouteWithChildren,
  ShareTokenRoute: ShareTokenRoute,
  BoardsIndexRoute: BoardsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
